### ISSUE TITLE
missing background image for kodi remote

### ISSUE THREAD

**Issue by leothlon** [sharetheloveio/sharethelove.io#59]
The background image "/local/banners/empty_long_placeholder.png" for kodi remote is missing from the icon pack, when i tried with another image it wont look right...

**Comment by ludeeus** [comment]
The background is not an icon and will therefore not be in the icon pack ;)
For this card, any transparent image will do, you can use an image editor of your choice to make this :)

Lovelace is in continuous fast changing development if the result is a bit off from the reference here it could be due to that.
